# Generated by Django 4.1.2 on 2022-10-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='personelApp.department'),
        ),
    ]
